coverage:
  precision: 2
  round: up
  range: "50...90"
  status:
    project:
      default:
        threshold: 1
  ignore:
    - "testutils"
    - "p2p"
    - "**/*.pb.go"  # protobuf generated go files
    